"""Project-wide defaults and persisted calculation versions."""

DEFAULT_ANALYSIS_BARS = 300
DEFAULT_RESEARCH_BARS = 320
DEFAULT_CHART_BARS = 500
MIN_PATTERN_BARS = 260

SCHEMA_VERSION = "2"
INDICATOR_VERSION = "2.0.0"
PATTERN_ENGINE_VERSION = "2.0.0"

